### ISSUE TITLE
TOML DataTest Issue

### ISSUE THREAD

**Issue by rprospero** [disorderedmaterials/dissolve#1460]
I'm having an issue converting the test for [tests/exchangeable/watermeth.txt](https://github.com/disorderedmaterials/dissolve/blob/develop/tests/exchangeable/watermeth.txt) into a [TOML file](https://gist.github.com/rprospero/e37a2722416e7853e462cc06526614c1).  The `data1D` keyword adds the Data1DStoreKeyword to the module.  The first example of this occurs in line 13 of the TOML file.  When the file is parsed back in, the data is correctly added back into the Data1D keyword on the module and could be accesed from there.  However, on [line 29 of src/modules/datatest/process.cpp](https://github.com/disorderedmaterials/dissolve/blob/23c4acabd638c2a598f7da6044347f0c211d3601/src/modules/datatest/process.cpp#L29), It searches the `processingModuleData` for the data set.  I cannot find any corresponding call to `realise` that would have populated `processingModuleData`, though it obviously exists somewhere, given that the test passes on the non-TOML version of the code.

The quick solution is to put in an override for `DataTestModule` where
it automatically add the data store keywords to the `processingModuleData`.  However, it feels like I'm missing something fundamental about populating this data structure.  The code would also be a fairly ugly hack, since that part of the parser currently does not have access to the `Dissolve` instance.

As a side note, would I be correct that the elements in `Data1DStore` must have unique tags?  If so, I can probably clean up the TOML file from looking like:

```toml
[[layers.Processing.modules."Total_weighted_S(Q)".data1D]]
tag = "HHH//WeightedSQ//Total"

[layers.Processing.modules."Total_weighted_S(Q)".data1D.data]
format = "xy"
filename = "../_data/epsr25/water300methanol600/watermeth.EPSR.u01"

[[layers.Processing.modules."Total_weighted_S(Q)".data1D]]
tag = "H5H//WeightedSQ//Total"

[layers.Processing.modules."Total_weighted_S(Q)".data1D.data]
format = "xy"
filename = "../_data/epsr25/water300methanol600/watermeth.EPSR.u01"

[layers.Processing.modules."Total_weighted_S(Q)".data1D.data.keywords]
y = 4
```

to

```toml
[layers.Processing.modules."Total_weighted_S(Q)".data1D."HHH//WeightedSQ//Total"]

[layers.Processing.modules."Total_weighted_S(Q)".data1D."HHH//WeightedSQ//Total".data]
format = "xy"
filename = "../_data/epsr25/water300methanol600/watermeth.EPSR.u01"

[layers.Processing.modules."Total_weighted_S(Q)".data1D."H5H//WeightedSQ//Total"]

[layers.Processing.modules."Total_weighted_S(Q)".data1D."H5H//WeightedSQ//Total".data]
format = "xy"
filename = "../_data/epsr25/water300methanol600/watermeth.EPSR.u01"

[layers.Processing.modules."Total_weighted_S(Q)".data1D."H5H//WeightedSQ//Total".data.keywords]
y = 4
```
